DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass

from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
import random
import string
from django.contrib.auth.hashers import make_password

from designers.models import Designers


def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'your userId and password is {0} {1}'.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^designers/',include('designers.urls')),
    url(r'^',include('customers.urls')),
    #url(r'^store/', include('store.urls')),
    url(r'^mail/',  admin.site.admin_view(Mail), name='Mail'),
    url(r'^andro/',include('apis.urls')),
    #url(r'^seller/',include('seller.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

customers/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name='customers'


urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^designs$', views.search,name='search'),
    url(r'^blogs$',views.blogs,name='blogs'),
    url(r'^job_description$',views.job,name='job'),
    url(r'^job_personal$',views.job2,name='job2'),
    url(r'^designer_select$',views.designer,name='designer'),
    url(r'^designer_selected$',views.designer_selected,name='designer_selected'),
    url(r'^otp', views.otp, name='otp'),
    url(r'^make_payment$', views.make_payment, name='make_payment'),
    url(r'^successfull$',views.successfull, name='successfull'),
    url(r'^login$',views.login, name='login'),
    url(r'^logout$',views.logout, name='logout'),
    url(r'^profile_details',views.profile_handler,name='profile_handler'),
    url(r'^update_post',views.update,name="update"),
    url(r'^howitworks',views.howitworks,name='howitworks'),
    url(r'^ourdesign$',views.ourdesign,name='ourdesign'),
    #url(r'^testing$',views.testblogs,name='testblogs'),
    url(r'^blogview/$', views.specific_blog, name='specific_blog'),
    url(r'^resend$', views.resend, name='resend'),
    url(r'^test$', views.test, name='test'),










]

seller/urls.py
from django.conf.urls import url

from . import views

app_name = 'seller'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^dashboard/$',views.dashboard,name='dashboard'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add_product/$', views.add, name='add'),

]

seller/models.py
from django.db import models


class Sellers(models.Model):
    name = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=300, null=True)
    password = models.CharField(max_length=10, null=True)




    contact = models.CharField(max_length=12,blank=True,null=True)
    emailid = models.EmailField(max_length=50)
    verified = models.BooleanField(default=False)


    def __str__(self):
        return self.name


#class fileupload(models.Model):

seller/forms.py
from django import forms


class SellerDetails(forms.Form):
    name = forms.CharField(max_length=15)
    emailid = forms.EmailField(max_length=50)
    contact = forms.CharField(max_length=12)
    address = forms.CharField()
    password = forms.CharField(max_length=1000)


class LoginCheck(forms.Form):
    emailid = forms.EmailField(max_length=50)
    password = forms.CharField(max_length=1000)


class ProductEntryForm(forms.Form):
    name = forms.CharField()
    company = forms.CharField()
    price = forms.DecimalField()
    availability = forms.CharField()
    category = forms.CharField()
    other = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(ProductEntryForm, self).__init__(*args, **kwargs)
        self.fields['other'].required = False


class ProductSearchForm(forms.Form):
    searchfield=forms.CharField()

seller/views.py
from django.shortcuts import render

from .models import *
from store.models import Products, Category
from .forms import *


def index(request):
    if request.session.has_key('seller'):
        id = request.session['seller']
        dbuser = Sellers.objects.filter(id=id)
        products = Products.objects.filter(seller=dbuser[0])
        categories = Category.objects.all()
        if dbuser:
            context = {
                'dbuser': dbuser,
                'products':products,
                'categories': categories,
            }
            return render(request, 'seller/dashboard.html',context)
    return render(request, 'seller/index.html')


def register(request):
    if request.method == 'POST':
        MyRegisterForm = SellerDetails(request.POST)
        print(MyRegisterForm.errors)
        if MyRegisterForm.is_valid():
            name = MyRegisterForm.cleaned_data['name']
            emailid = MyRegisterForm.cleaned_data['emailid']
            contact = MyRegisterForm.cleaned_data['contact']
            address = MyRegisterForm.cleaned_data['address']
            password = MyRegisterForm.cleaned_data['password']
            dbuser = Sellers(name=name,emailid=emailid,address=address,password=password)
            dbuser.contact = contact
            dbuser.save()
            print(dbuser)

    return render(request, 'seller/register.html')


def dashboard(request):
    if request.session.has_key('seller'):
        print('yo')
        id = request.session['seller']
        dbuser = Sellers.objects.filter(id=id)
        products=Products.objects.filter(seller=dbuser[0])

        print(products)

        categories = Category.objects.all()


        if dbuser:
            context = {
                'dbuser': dbuser,
                'products': products,
                'categories': categories,
            }
            return render(request, 'seller/dashboard.html',context)
    if request.method == 'POST':
        MyLoginForm = LoginCheck(request.POST)
        if MyLoginForm.is_valid():
            emailid = MyLoginForm.cleaned_data['emailid']
            password = MyLoginForm.cleaned_data['password']
            dbuser = Sellers.objects.filter(emailid=emailid, password=password)
            print(dbuser)
            products = Products.objects.filter(seller=dbuser[0])
            if dbuser:
                if dbuser[0].verified :
                    request.session['seller'] = dbuser[0].id
                    categories = Category.objects.all()
                    context = {
                        'dbuser':dbuser,
                        'products':products,
                        'categories': categories,
                    }
                    return render(request, 'seller/dashboard.html',context)
                else:
                     return render(request, 'seller/registered.html')
    return render(request, 'seller/index.html')

def logout(request):
    try:
        del request.session['seller']
    except:
        pass
    return render(request, 'seller/index.html')


def add(request):
    if request.session.has_key('seller'):
        id = request.session['seller']
        if request.method == 'POST':

            MyLoginForm = ProductEntryForm(request.POST)
            print(MyLoginForm.errors)
            if MyLoginForm.is_valid():
                name = MyLoginForm.cleaned_data['name']
                company = MyLoginForm.cleaned_data['company']
                price = MyLoginForm.cleaned_data['price']
                availability=MyLoginForm.cleaned_data['availability']
                cat = MyLoginForm.cleaned_data['category']
                other = MyLoginForm.cleaned_data['other']

                dbuser = Sellers.objects.filter(id=id)
                if cat == "Other":
                    categ = Category()
                    categ.name = other
                    categ.save()

                if not cat == "Other":
                    category = Category.objects.filter(name=cat)
                else:
                    category = Category.objects.filter(name=other)


                if Products.objects.filter(name=name, company=company, seller=dbuser):
                    x=Products.objects.filter(name=name, company=company)[0]

                if Products.objects.filter(name=name, company=company, category=category, seller=dbuser[0]):
                    x=Products.objects.filter(name=name, company=company, category=category)[0]

                    x.price=price
                    x.availability=availability
                    x.save(update_fields=['price','availability'])
                else:
                    product = Products()
                    product.productID = "GBDP{0}{1}".format(id, Products.objects.count())
                    product.name = name
                    product.company = company
                    product.price = price
                    product.availability = availability
                    product.category = category[0]
                    product.seller = dbuser[0]
                    product.save()

                categories = Category.objects.all()
                products=Products.objects.filter(seller=dbuser[0])
                context = {
                    'dbuser': dbuser,
                    'products':products,
                    'categories': categories,
                }
                return render(request, 'seller/dashboard.html', context)

        else:
           dbuser = Sellers.objects.filter(id=id)
           mysearch=ProductSearchForm(request.GET)
           if mysearch.is_valid():
               search=mysearch.cleaned_data['searchfield']

               productlist=list(Products.objects.filter(name__icontains=search, seller=id))

               productlist=list(Products.objects.filter(name__icontains=search,seller=id))
               productlist.extend(list(Products.objects.filter(company__icontains=search,seller=id)))
               categories = Category.objects.all()


               context = {
                   'dbuser': dbuser,
                   'products': productlist,
                   'categories': categories,
               }
               return render(request, 'seller/dashboard.html', context)
           else:
               products = Products.objects.filter(seller=dbuser[0])
               categories = Category.objects.all()
               context = {
                   'dbuser': dbuser,
                   'products': products,
                   'categories': categories,
               }
               return render(request, 'seller/dashboard.html', context)




    else:
        return render(request, 'seller/index.html')

seller/templates/seller/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>

    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
</head>
<body>


     <u><h1 align="center">     {% for user in dbuser %}
            {{ user.name }}
          {% endfor %}
     </h1>
     </u>
      <br>
     <form method="get"  action="{% url 'seller:add'  %}" style="align-content: flex-end;align-self: right ;height:30px;width: 35%;" float="right">

         <input type="text" name="searchfield">
         <button type="submit" >Search</button>
     </form>
     Enter or update product:
      <form method="post" action="{% url 'seller:add'  %}" >
          {% csrf_token %}
          <br>name
          <input type="text" name="name" required>
          company:
          <input type="text" name="company" required>
          price:
          <input type="text" name="price" required>
          category:
          <select class="selectpicker" name="category" onchange="showfield(this.options[this.selectedIndex].value)" required>
              {% for category in categories %}
              <option value="{{ category.name }}">{{ category.name }}</option>
              {% endfor %}
              <option value="Other">Other</option>
          </select>
          <div id="select-other"></div>
          <br>
          <br>
          availabile:

          <select name="availability"  value="True">

          <option>True</option>
           <option>False</option>
      </select>
          <br>
          <br>
          <button type="submit">Add/Update</button>
      </form>
    <table>
      {% for product in products %}
         <tr>
            <td>
                {{ product.name }}
            </td>
            <td>
                {{ product.company }}
            </td>
            <td>
                {{ product.price }}
            </td>
            <td>
                {{ product.availability }}
            </td>
            <td>
                {{ product.category.name }}
            </td>
         </tr>
      {% endfor %}
    </table>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'seller/js/site.js' %}"></script>
</body>
</html>

seller/templates/seller/index.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>Seller Portal</title>
    </head>
    <body>
        <h1>Seller's Portal</h1>
        <form method="post" action="{% url 'seller:dashboard' %}">
            {%  csrf_token %}
            emailid: <input type="email" name="emailid">
            <br>
            <br>
            password: <input type="password" name="password">
            <br>
            <button type="submit">Login</button>
         </form>
        <br>
        <br>
        <br>
        <a href="{% url 'seller:register' %}">Click here to register</a>

    </body>
</html>

seller/templates/seller/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Seller Registration</title>
</head>
<body>
    <form method="post" action="{% url 'seller:register' %}">
        {%  csrf_token %}
        Brand Name: <input type="text" name="name">
        <br>
        Emailid: <input type="email" name="emailid">
        <br>
        Contact: <input type="text" name="contact">
        <br>
        Address: <textarea name="address"></textarea>
        <br>
        Password: <input type="password" name="password">
        <br>
        Confirm Password: <input type="password" name="confirmpassword">
        <br>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

seller/templates/seller/registered.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registered</title>
</head>
<body>
    <p>You will be verified soon</p>
    <a href="{% url 'customers:index' %}">home</a>
</body>
</html>