DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass

from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
import random
import string
from django.contrib.auth.hashers import make_password

from designers.models import Designers


def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'your userId and password is {0} {1}'.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^designers/',include('designers.urls')),
    url(r'^',include('customers.urls')),
    #url(r'^store/', include('store.urls')),
    url(r'^mail/',  admin.site.admin_view(Mail), name='Mail'),
    url(r'^andro/',include('apis.urls')),
    #url(r'^seller/',include('seller.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^getverified/$', views.getverified, name='getverified'),
    url(r'^notverified/$', views.notverified, name='notverified'),
    url(r'^verification/$', views.verification, name='verification'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^myprofile/$', views.myprofile, name='myprofile'),
    url(r'^searchres/$', views.searchres, name='searchres'),
    url(r'^ajaxsearch/$', views.ajaxsearch, name='ajaxsearch'),
    url(r'^products/(?P<product_name>[ \t\n\r\f\vA-Za-z]+)/$', views.products, name='products'),
    url(r'^addtocart/$', views.add_to_cart, name='addtocart'),
    url(r'^cart/$', views.view_cart, name='viewcart'),
    url(r'^delitem/$', views.del_item, name='delitem'),
    url(r'^updateitem/$', views.update_item, name='updateitem'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^delcart/$', views.delcart, name='delcart'),
]

store/forms.py
from django import forms

from designers.models import Designers


class StoreLoginForm(forms.Form):
    designerID = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput())


class VerificationForm(forms.Form):
    verificationImage = forms.ImageField()

    def __init__(self, *args, **kwargs):
        super(VerificationForm, self).__init__(*args, **kwargs)
        self.fields['verificationImage'].required = False


class SearchForm(forms.Form):
    select = forms.CharField()
    search = forms.CharField()


class AddressForm(forms.Form):
    name = forms.CharField()
    firmname = forms.CharField()
    number = forms.IntegerField
    email = forms.EmailField()
    city = forms.CharField()
    state = forms.CharField()
    address = forms.CharField()
    pincode = forms.IntegerField()

store/views.py
from django.contrib.auth.hashers import check_password
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.cache import cache_control

from designers.models import Designers
from . models import VerifiedDesigners, Products, Category, Bills, Purchases, ShippingAddress
from . forms import StoreLoginForm, VerificationForm, SearchForm


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    if request.session.has_key('designerID'):
        designerID = request.session['designerID']
        dbuser = Designers.objects.filter(designerID=designerID)
        categories = Category.objects.all()

        if dbuser:
            vdes = VerifiedDesigners.objects.filter(designer=dbuser[0])
            if 'cart' in request.session:
                cart = request.session['cart']
            else:
                cart = {}
            count = len(cart)
            context = {
                'dbuser': dbuser[0],
                'categories': categories,
                'cartcount': count,
            }

            if vdes:
                if not vdes[0].verified:
                    return render(request, 'store/notverified.html', context)

                return render(request, 'store/dashboard.html', context)

            VerifiedDesigners.objects.create(designer=dbuser[0])
            return render(request, 'store/notverified.html', context)

    context = {}
    return render(request, 'store/index.html', context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def dashboard(request):
    designerID = ""
    password = ""

    if request.method == "POST":
        if request.session.has_key('designerID'):
            designerID = request.session['designerID']
            dbuser = Designers.objects.filter(designerID=designerID)
            categories = Category.objects.all()
            if dbuser:
                vdes = VerifiedDesigners.objects.filter(designer=dbuser[0])
                if 'cart' in request.session:
                    cart = request.session['cart']
                else:
                    cart = {}
                count = len(cart)
                context = {
                    'dbuser': dbuser[0],
                    'categories': categories,
                    'cartcount': count,
                }

                if vdes:
                    if not vdes[0].verified:
                        return render(request, 'store/notverified.html', { 'dbuser': dbuser[0] })

                    return render(request, 'store/dashboard.html', context)

                VerifiedDesigners.objects.create(designer=dbuser)
                return render(request, 'store/notverified.html', { 'dbuser': dbuser[0] })
        
        LoginForm = StoreLoginForm(request.POST)
        form_errors = LoginForm.errors
        print(form_errors)

        if LoginForm.is_valid():
            designerID = LoginForm.cleaned_data['designerID']
            password = LoginForm.cleaned_data['password']
            print(designerID)
            dbuser = Designers.objects.filter(designerID=designerID)

            if dbuser and check_password(password, dbuser[0].password):
                vdes = VerifiedDesigners.objects.filter(designer=dbuser[0])
                user = dbuser[0]
                request.session['designerID'] = designerID
                categories = Category.objects.all()
                if 'cart' in request.session:
                    cart = request.session['cart']
                else:
                    cart = {}
                count = len(cart)
                context = {
                    'dbuser': user,
                    'categories': categories,
                    'cartcount': count,
                }
                if vdes:
                    if not vdes[0].verified:
                        return render(request, 'store/notverified.html', { 'dbuser': user })
                    return render(request, 'store/dashboard.html', context)

                VerifiedDesigners.objects.create(designer=dbuser[0])
                return render(request, 'store/notverified.html', { 'dbuser': user })
            if not dbuser:
                print("Not user")
                context = {
                    'error': "DesignerID or Password incorrect!"
                }
                return render(request, 'store/index.html', context)
        else:
            print("Not valid")
            return render(request, 'store/index.html', {})

    else:
        LoginForm = StoreLoginForm(request.GET)
        if request.session.has_key('designerID'):
            designerID = request.session['designerID']
            dbuser = Designers.objects.filter(designerID=designerID)
            categories = Category.objects.all()
            if 'cart' in request.session:
                cart = request.session['cart']
            else:
                cart = {}
            count = len(cart)
            if dbuser:
                vdes = VerifiedDesigners.objects.filter(designer=dbuser[0])
                context = {
                    'dbuser': dbuser[0],
                    'categories': categories,
                    'cartcount': count,
                }
                if vdes:
                    if not vdes[0].verified:
                        return render(request, 'store/notverified.html', { 'dbuser': dbuser[0] })
                    return render(request, 'store/dashboard.html', context)

                VerifiedDesigners.objects.create(designer=dbuser[0])
                return render(request, 'store/notverified.html', { 'dbuser': dbuser[0] })
        return render(request, 'store/index.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def getverified(request):
    return render(request, 'store/getverified.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def notverified(request):
    return render(request, 'store/notverified.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def verification(request):
    if not request.session.has_key('designerID'):
        context = {
            'errors': "Please login to continue"
        }
        return render(request, 'store/index.html', context)

    verificationImage = None
    if request.method == "POST":
        verform = VerificationForm(request.POST)
        print(verform.errors)

        if verform.is_valid():
            verificationImage = request.FILES['verificationImage']
            if request.session.has_key('designerID'):
                designerID = request.session['designerID']
                designer = Designers.objects.filter(designerID=designerID)
                dbuser = VerifiedDesigners.objects.filter(designer=designer[0])
                user = VerifiedDesigners.objects.get(designer=designer[0])
                user.document = verificationImage

                user.save(update_fields=['document'])

                context = {
                    'dbuser': designer
                }
                return render(request, 'store/verification.html', context)
            else:
                context = {
                    'errors': "Please login to continue"
                }
                return render(request, 'store/index.html', context)
        else:
            print("invalid form")

    else:
        verform = VerificationForm(request.GET)
        return render(request, 'store/getverified.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout(request):
    try:
        del request.session['designerID']
    except:
        pass
    context = {
        'error': "You have been successfully logged out."
    }
    return render(request, 'store/index.html', context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def myprofile(request):
    if not request.session.has_key('designerID'):
        context = {
            'errors': "Please login to continue"
        }
        return render(request, 'store/index.html', context)

    designerID = request.session['designerID']
    designer = Designers.objects.filter(designerID=designerID)

    if designer:
        verdes = VerifiedDesigners.objects.filter(designer=designer[0])
        context = {
            'dbuser': designer[0],
        }

        if not verdes[0].verified:
            return render(request, 'store/notverified.html', context)

        context = {
            'dbuser': designer[0],
            'vdes': verdes[0],
        }
        return render(request, 'store/myprofile.html', context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def searchres(request):
    selectpicker = ""
    search = ""
    product_list = []

    if request.session.has_key('designerID'):
        designerID = request.session['designerID']
        dbuser = Designers.objects.filter(designerID=designerID)

        if dbuser:
            vdes = VerifiedDesigners.objects.filter(designer=dbuser[0])

        SearchF = SearchForm(request.GET)
        form_errors = SearchF.errors
        print(form_errors)

        if SearchF.is_valid():
            select = SearchF.cleaned_data['select']
            search = SearchF.cleaned_data['search']
            if not select == "All Categories":
                category = Category.objects.filter(name=select)
                product_list = Products.objects.filter(category=category[0], name__icontains=search).order_by('price')

            else:
                product_list = Products.objects.filter(name__icontains=search)

        return render(request, 'store/search.html', { 'filter': product_list })


def ajaxsearch(request):
    SearchF = SearchForm(request.GET)
    form_errors = SearchF.errors
    print(form_errors)
    product_list = []
    if SearchF.is_valid():
        select = SearchF.cleaned_data['select']
        search = SearchF.cleaned_data['search']

        if not select == "All Categories":

store/templates/store/addaddress.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Add Address</title>
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
</head>
<body>
    <h1>Add Address</h1>
    <form class="form-horizontal" action="{% url 'store:checkout' %}" method="post">
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Firm Name</label>
            <input type="text" class="form-control" placeholder="Firm Name">
        </div>
        <div class="form-group">
            <label class="control-label">Phone Number</label>
            <input type="number" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" class="form-control" placeholder="Name">
        </div>
    </form>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

store/templates/store/cart.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Cart</title>

    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">

</head>
<body>

    {% for qty, product in products.items %}
    <div>
        Name: {{ product.name }} <br>
        Quantity: <input type="number" id="{{ product.id }}" value="{{ qty }}"> <br>
        <button class="btn btn-danger" value="{{ product.id }}">Delete</button>
    </div><br><br>
    {% endfor %}
    <br>
    <a class="btn btn-success" href="{% url 'store:checkout' %}">Checkout Cart</a>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'store/js/cart.js' %}"></script>
</body>
</html>

store/templates/store/dashboard.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ghar Banao Store</title>

    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">

</head>

<body>

    {% if dbuser %}


    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-1">

                <form class="navbar-form navbar-left" action="{% url 'store:searchres' %}" method="get">{% csrf_token %}
                    <div class="input-group">
                        <div class="input-group-btn">
                            <select class="selectpicker" id="select" name="select" style="display: none;">
                                <option>All Categories</option>
                                {% for category in categories %}
                                <option>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div><!-- /btn-group -->
                        <input type="text" autocomplete="off" class="form-control" id="search" placeholder="Search for products" name="search">

                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                        </span>
                    </div>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Request Items</a></li>
                    <li><a href="#">Track Orders</a></li>
                    <li><a href="{% url 'store:viewcart' %}">Cart ({{ cartcount }})</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{dbuser.name}}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">My Orders</a></li>
                            <li><a href="#">My Transactions</a></li>
                            <li><a href="#">My Lists</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">My Requests</a></li>
                            <li><a href="#">Recommendations</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'store:myprofile' %}">My Account</a></li>
                            <li><a href="{% url 'store:logout' %}">Sign Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div>
        <ul id="ajaxsearch"></ul>
    </div>

    {% endif %}

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'store/js/ajax.js' %}"></script>

</body>
</html>

store/templates/store/getverified.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
    
    <head>
    
        <meta charset="UTF-8">
    
        <title>Ghar Banao Store</title>
    
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    
    </head>
    
    <body>
        <h1>Get Verified</h1>
        <form name="form" action="{% url 'store:verification' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div>
                <p>Upload:</p>
                <input type="file" name="verificationImage" />
            </div>
            <div>
                <button type="submit" value="Submit">Submit</button>
            </div>
        </form>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    </body>

</html>

store/templates/store/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <title>Ghar Banao Store</title>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700">
    <link rel="stylesheet" href="{% static 'store/css/storelogin.css' %}">
</head>
<body class="align">

    <div class="grid">
        <div style="width:300px;">
            <img src="{% static 'store/img/gbs.png' %}">
        </div>
        <div class="logout">
            {% if error %}
            <span>{{error}}</span><br><br>
            {% endif %}
        </div>

      <form action="{% url 'store:dashboard' %}" method="POST" class="form login"> {% csrf_token %}

        <div class="form__field">
          <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Designer ID</span></label>
          <input id="login__username" type="text" name="designerID" class="form__input" placeholder="Designer ID" required>
        </div>

        <div class="form__field">
          <label for="login__password"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use></svg><span class="hidden">Password</span></label>
          <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
        </div>

        <div class="form__field">
          <input type="submit" value="Sign In">
        </div>

      </form>

    </div>

    <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
</body>
</html>

store/templates/store/notverified.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>
    <title>Login Error</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'store/css/notverified.css' %}">
</head>
<body>
    <center>
        <div id="window" align="">
            <img src="{% static 'store/img/error.png' %}">
            {% if dbuser %}

            <p>DesignerID <span> {{ dbuser.designerID }} </span> is not verified to use GharBanao Store yet.<br> Click continue to go to the verification page.</p>
            <a id="continue" href="{% url 'store:getverified' %}">continue</a>

            {% endif %}
        </div>
    </center>

</body>
</html>

store/templates/store/search.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Search Results</title>
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
</head>
<body>
    <br><br><br><br><br><br>
    <ul>

        {% for product in filter %}

        <li><a href="{% url 'store:products' product.name %}"> {{ product.name }}</a></li>

        {% endfor %}
    </ul>

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
</body>
</html>