DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass

from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
import random
import string
from django.contrib.auth.hashers import make_password

from designers.models import Designers


def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'your userId and password is {0} {1}'.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^designers/',include('designers.urls')),
    url(r'^',include('customers.urls')),
    #url(r'^store/', include('store.urls')),
    url(r'^mail/',  admin.site.admin_view(Mail), name='Mail'),
    url(r'^andro/',include('apis.urls')),
    #url(r'^seller/',include('seller.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

designers/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name='designers'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register/$', views.DesignerCreate.as_view(), name='register'),
    url(r'login/$', views.login, name='login'),
    url(r'dashboard/$', views.registeration, name='registeration'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'registerconf/$', views.regcon, name='regcon'),
    url(r'our_designers', views.designersview, name='ourDes'),
    url(r'change_password/$', views.change_password, name='password_change'),
    url(r'wrong_password/$', views.wrongPassword, name='wrongPassword'),
    url(r'create_blog/$', views.blog, name='blog'),
    url(r'view_blogs/$',views.blog_search,name='blogsearch'),
    url(r'^(?P<status>[0-9]+)/$',views.next,name='next'),
    url(r'^dp_change/$',views.edit_dp,name='edit_dp'),
    url(r'^address_change/$',views.edit_address,name='edit_address'),
    url(r'^about_change/$',views.edit_about,name='edit_about'),
    url(r'^jobs/$',views.myjobs,name='myjobs'),
    url(r'^editjob/$',views.editjob,name='editjob'),
    url(r'^update/$',views.update,name='update'),
    url(r'^requestitem',views.requestitem,name='requestitem'),
    #url(r'^design/$', views.designs, name='design'),
    url(r'^login1/$', views.login1, name='login1'),
    url(r'^logout1/$', views.logout1, name='logout1'),
    url(r'^edit_des/$',views.edit_designs,name='edit_designs'),
    url(r'^forgotpass/$', views.forgotpass, name='fp'),
    url(r'^forgotpass/update/$', views.passmatch, name='fpu'),
    url(r'^resendotp/$', views.resendotp, name='reotp'),
    url(r'^test/$', views.test, name='test'),



]

designers/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render
from django.views.decorators.cache import cache_control
from django.views.decorators.cache import never_cache
from django.core.mail import send_mail
from django.conf import settings
from . models import Designers,Blogs,BlogLiked,Comments,Designs,Rawpass
from . forms import *
from django.contrib.auth.hashers import make_password,check_password
from django.views.generic.edit import CreateView
from customers.models import *
from . forms import DesignerDetails, ConfirmPasswordForm, BlogForm, Comment, DpForm, AboutForm, DesignsForm
from . models import Designers, Blogs, BlogLiked, Comments, Designs, Rawpass
import random
import string

# Create your views here.
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    if request.session.has_key('designerID'):
        try:
            del request.session['selectedjob']
        except:
            pass
        designerID = request.session['designerID']
        dbuser = Designers.objects.filter(designerID=designerID)
        blogList = Blogs.objects.filter(author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by('-dated')
        if dbuser[0].PortfolioFilled:
            context = {
                'dbuser': dbuser,
                'blogList':blogList
            }

            return render(request, 'designers/loggedin.html', context)
        elif dbuser:
            del request.session['designerID']
    context={

    }
    return render(request,'designers/index.html',context=context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def registeration(request):

    designerID=""
    password=""
    if request.method == "POST":
        if request.session.has_key('designerID'):
            try:
                del request.session['selectedjob']
            except:
                pass
            designerID = request.session['designerID']
            dbuser = Designers.objects.filter(designerID=designerID)
            blogList = Blogs.objects.filter(author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by('-dated')
            if dbuser and dbuser[0].PortfolioFilled==True:
                context = {
                    'dbuser': dbuser,
                    'blogList': blogList
                }
                return render(request, 'designers/loggedin.html', context)
        # Get the posted form
        MyRegisterForm = DesignerDetails(request.POST)
        form_errors= MyRegisterForm.errors
        content={
            'form':MyRegisterForm,
            'errors':  form_errors
        }
        print( MyRegisterForm.errors)
        if MyRegisterForm.is_valid():
            designerID=MyRegisterForm.cleaned_data['designerID']

            password=MyRegisterForm.cleaned_data['password']

            print(designerID)
            dbuser = Designers.objects.filter(designerID=designerID)
            if dbuser and check_password(password,dbuser[0].password):
                user = dbuser[0]
                #profilepic = user.profilepic.url
                request.session['designerID'] = designerID
                blogList = Blogs.objects.filter( author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by( '-dated')
                context = {
                    'dbuser': dbuser,
                    'blogList': blogList
                }
                if dbuser[0].PortfolioFilled == False:
                    context1 = {
                        'status': dbuser[0].status
                    }
                    return render(request, 'designers/dashboard.html', context1)
                return render(request, 'designers/loggedin.html', context)
            elif dbuser:
                return render(request, 'designers/register.html', {})
            if not dbuser:
                print("Not user")
                return render(request, 'designers/register.html', {})

        else:
            print("not valid")
            return render(request, 'designers/register.html', {})
    else:
        MyRegisterForm=DesignerDetails(request.GET)
        if request.session.has_key('designerID'):
            try:
                del request.session['selectedjob']
            except:
                pass
            designerID = request.session['designerID']
            dbuser = Designers.objects.filter(designerID=designerID)
            blogList = Blogs.objects.filter(author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by('-dated')
            context = {
                'dbuser': dbuser,
                'blogList': blogList
            }
            if dbuser[0].PortfolioFilled:
                return render(request, 'designers/loggedin.html', context)
            if dbuser[0].PortfolioFilled == False:
                context1 = {
                    'status': dbuser[0].status
                }
                return render(request, 'designers/dashboard.html', context1)


        return render(request, 'designers/register.html', {})

class DesignerCreate(CreateView):
    model=Designers
    fields = ['name','firmname','contact','email','address']


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout(request):
    try:
        del request.session['designerID']
    except:
        pass
    return render(request, 'designers/logout.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login(request):
    if request.session.has_key('designerID'):
        try:
            del request.session['selectedjob']
        except:
            pass
        designerID = request.session['designerID']
        dbuser = Designers.objects.filter(designerID=designerID)
        if dbuser and dbuser[0].PortfolioFilled:
            user = dbuser[0]
            profilepic = user.profilepic.url
            blogList = Blogs.objects.filter(author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by('-dated')
            context = {
                'dbuser': dbuser,
                'blogList': blogList
            }
            return render(request, 'designers/loggedin.html', context)
        if dbuser and dbuser[0].PortfolioFilled == False:
            context1 = {
                'status': dbuser[0].status
            }
            return render(request, 'designers/dashboard.html', context1)

    return render(request, 'designers/register.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def regcon(request):
    if request.session.has_key('designerID'):
        try:
            del request.session['selectedjob']
        except:
            pass
        designerID = request.session['designerID']
        dbuser = Designers.objects.filter(designerID=designerID)
        if dbuser[0].PortfolioFilled:
            blogList = Blogs.objects.filter( author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by('-dated')
            context = {
                'dbuser': dbuser,
                'blogList': blogList
            }
            return render(request, 'designers/loggedin.html', context)
    context={

    }
    return render(request,'designers/regconfirm.html',context=context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def designersview(request):
    all_designers=Designers.objects.filter(PortfolioFilled=True).order_by('-points')
    context = {'all_designers':all_designers}
    return render(request, 'designers/our_designers.html',context)



@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def change_password(request):
    if not request.session.has_key('designerID'):
        return render(request, 'designers/register.html', {})
    old_password=""
    new_password=""
    if request.session.has_key('designerID') and request.method == "POST":
        try:
            del request.session['selectedjob']
        except:
            pass
        MyForm=ConfirmPasswordForm(request.POST)
        print(MyForm.errors)
        if MyForm.is_valid():
            old_password=MyForm.cleaned_data['old_password']
            new_password = MyForm.cleaned_data['new_password']
            if request.session.has_key('designerID'):
                designerID = request.session['designerID']
                user = Designers.objects.get(designerID=designerID)
                if user and check_password(old_password,user.password):
                    user.password = make_password(new_password)
                    rawp = Rawpass.objects.filter(designer=user)
                    rawp[0].rawpass = MyForm.cleaned_data['new_password']
                    rawp[0].save(update_fields=['rawpass'],force_update=True)
                    print(rawp[0].rawpass)
                    if user.status == 4:
                        user.status = 5
                        user.PortfolioFilled = True
                        user.save(update_fields=['password', 'status', 'PortfolioFilled'])
                        return render(request, 'designers/succesfull.html', {})
                    else:
                        user.save(update_fields=['password'])
                    dbuser = Designers.objects.filter(designerID=designerID)
                    blogList = Blogs.objects.filter(author=Designers.objects.filter(designerID=request.session['designerID'])[0].email).order_by('-dated')
                    if dbuser[0].PortfolioFilled:
                        context = {
                            'dbuser': dbuser,
                            'blogList': blogList
                        }
                        return render(request, 'designers/loggedin.html', context)
                else:
                    print('not user ')
                    del request.session['designerID']
                    return render(request, 'designers/WrongPassword.html', {})

designers/templates/designers/1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration - GharBanao</title>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'designers/css/designerinfo.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'designers:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div style="position: absolute; right: 7vw;top: 25px;">


            <a href="{% url 'designers:logout' %}" class="btn my_project" >Logout<span class="sr-only">(current)</span></a></li>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container page" id="page">
    <center>
        <div class="row no-margin container-fluid main" style="height: 420px">
            <form method="post" action="{% url 'designers:next' status %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row" style="background: #123c88; border-radius: 6px 6px 0px 0px"><h3 class="col-xs-12" style="color: white">Our customers would like to see you</h3></div><br>

                <div class="row no-margin"> <h5>Upload a photo:</h5> </div>

                <div class="row no-margin">
                    <center>
                        <div class="row no-margin preview">
                            <img id="blah" src="{% static 'customers/img/face1.jpg'%}">

                            <input type="file" id="imgInp" name="profilepic">

                        </div>
                    </center>
                </div>
                <button type="submit"><b>Save and continue</b></button>

            </form>

        </div>
    </center>
</div>
<script>
    function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp").change(function(){
    readURL(this);
});
</script>

</body>
</html>

designers/templates/designers/2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration - GharBanao</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">

    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <!--<link rel="stylesheet" href="css/profile.css" >-->
    <link rel="stylesheet" href="{% static 'designers/css/designerinfo.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>


</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'designers:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div style="position: absolute; right: 7vw;top: 25px;">


            <a href="{% url 'designers:logout' %}" class="btn my_project" >Logout<span class="sr-only">(current)</span></a></li>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<div class="container page" id="page">
    <center>
        <div class="row no-margin container-fluid files" style="">
            <div class="row" style="background: #123c88; border-radius: 6px 6px 0px 0px"><h3 class="col-xs-12" style="color: white">Upload three of your most appreciated designs</h3></div><br>
            <form method="post" action="{% url 'designers:next' status %}" enctype="multipart/form-data" >
                {% csrf_token %}
                <div class="col-sm-4">
                    <div class="row no-margin preview">
                        <img id="blah1" src="{% static 'customers/img/face1.jpg'%}">
                        <input type="file" id="imgInp1" name="design1">
                    </div>

                    <br>
                    <select name="design1type">
                        <option>
                            Traditional
                        </option>
                        <option>
                            Modern
                        </option>
                        <option>
                            Minimalistic
                        </option>
                        <option>
                            Contemporary
                        </option>
                        <option>
                            Industrial
                        </option>
                        <option>
                            MidCenturyModern
                        </option>
                        <option>
                            Scandinian
                        </option>
                        <option>
                            Bohemian
                        </option>
                        <option>
                            Retro
                        </option>
                    </select>
                </div>


                <div class="col-sm-4">


                    <div class="row no-margin preview">
                        <img id="blah2" src="{% static 'customers/img/face1.jpg'%}">
                        <input type="file"  id="imgInp2" name="design2">

                    </div>
                    <br>
                    <select name="design2type">
                        <option>
                            Traditional
                        </option>
                        <option>
                            Modern
                        </option>
                        <option>
                            Minimalistic
                        </option>
                        <option>
                            Contemporary
                        </option>
                        <option>
                            Industrial
                        </option>
                        <option>
                            MidCenturyModern
                        </option>
                        <option>
                            Scandinian
                        </option>
                        <option>
                            Bohemian
                        </option>
                        <option>
                            Retro
                        </option>
                    </select>

                </div>

                <div class="col-sm-4">
                    <div class="row no-margin preview">
                        <img id="blah3" src="{% static 'customers/img/face1.jpg'%}">
                        <input type="file" id="imgInp3" name="design3">

                    </div>
                    <br>
                    <select name="design3type">
                        <option>
                            Traditional
                        </option>
                        <option>
                            Modern
                        </option>
                        <option>
                            Minimalistic
                        </option>
                        <option>
                            Contemporary
                        </option>
                        <option>
                            Industrial
                        </option>
                        <option>
                            MidCenturyModern
                        </option>
                        <option>
                            Scandinian
                        </option>
                        <option>
                            Bohemian
                        </option>
                        <option>
                            Retro
                        </option>
                    </select>
                </div>


                <button type="submit">Next</button>
            </form>


        </div>
    </center>
</div>
<script>
    function readURL1(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah1').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp1").change(function(){
    readURL1(this);
});
</script>
<script>
    function readURL2(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah2').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp2").change(function(){
    readURL2(this);
});
</script>
<script>
    function readURL3(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah3').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp3").change(function(){
    readURL3(this);
});
</script>

</body>
</html>

designers/templates/designers/changePassword.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password - GharBanao</title>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'designers/css/designerinfo.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
    <script src="{% static 'customers/js/jquery.min.js' %}"></script>
    <script src="{% static 'customers/js/bootstrap.min.js' %}"></script>
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'designers:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div style="position: absolute; right: 7vw;top: 25px;">


            <a href="{% url 'designers:logout' %}" class="btn my_project" >Logout<span class="sr-only">(current)</span></a></li>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<div class="container page" id="page">
    <center>
        <div class="row no-margin container-fluid main">
            <div class="row" style="background: #123c88; border-radius: 6px 6px 0px 0px"><h3 class="col-xs-12" style="color: white">Change Password</h3></div><br>
            <form name = "form" action = "{% url 'designers:password_change' %}"  method = "POST"   id="opening"  onsubmit="return myFunction()">
                {% csrf_token %}

                <br>
                <input class="text-input" type = "password"  placeholder = "Current password" name = "old_password" />
                <br>
                <br>
                <input class="text-input" id ="pass1" type = "password" placeholder = "New Password" name = "new_password" >
                <br>
                <br>
                <input class="text-input" id ="pass2" type = "password"  placeholder = "Confirm Password"  >
                <br>
                <br>
                <div id="demo"></div>

                <script>
                    function myFunction() {
                    var pass1 = document.getElementById("pass1").value;
                    var pass2 = document.getElementById("pass2").value;
                    var ok = true;
                    if (pass1 != pass2) {

                    document.getElementById("demo").innerHTML = "Password do not match";
                    document.getElementById("pass1").style.borderColor = "#E34234";
                    document.getElementById("pass2").style.borderColor = "#E34234";

                    ok = false;
                    }

                    return ok;
                    }

                </script>

                        <button type = "submit" value = "Login"  >
                            <strong>Change Password</strong>
                        </button>
                <br>

            </form>
        </div>
    </center>
</div>


</body>
</html>

designers/templates/designers/dashboard.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome - GharBanao</title>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'designers/css/hello.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>


</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'designers:index' %}" ><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>
        <div style="position: absolute; right: 7vw;top: 25px;">
            <a href="{% url 'designers:logout' %}" class="btn my_project" >Logout<span class="sr-only">(current)</span></a></li>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container page" id="page">
    <center style="background: url({% static 'designers/img/welcome.jpg' %}) no-repeat center; background-size: cover; background-attachment: scroll;">
        <div class="row">
            <div class="col-xs-12 head">
                <h2 >Hello there! We are happy to have you onboard.</h2>
                <h4 >Following are the mandatory steps to build your GharBanao designer profile.</h4>
            </div>
        </div>
        <div class="row" align="center">
            <div align="left" class="col-xs-12 steps">
                <ul>
                    <li><div class="number" align="center">1</div><div class="content"> <h3>Add profile picture</h3> <h5>A profile without a profile picture won't catch much attention from the visitors. Isn't it?</h5></div></li><hr>
                    <li><div class="number" align="center">2</div><div class="content"> <h3>Upload designs </h3> <h5>A potential customer would definitely want to see your previous works. Make sure they like them.</h5></div></li><hr>
                    <li><div class="number" align="center">3</div><div class="content"> <h3>Write about you & your designs </h3> <h5>Because a visitor may like to know you a bit. And tell them the speciality about your designs</h5></div></li><hr>
                    <li><div class="number" align="center">4</div><div class="content"> <h3>Change password</h3> <h5>Don't feel safe with the default password? Change it so that no one else can have access to your account.</h5></div></li>
                </ul>
            </div>
            <div class="col-xs-12 head">
                <h5> Don't wish complete all the steps at one go? No problem. Login anytime you want and continue from where you left. Click the proceed button bellow to start.</h5>
            </div>
        </div>


        <div class="row proceed"><a href="{% url 'designers:next' status %}"><b> Proceed </b></a></div>
        <br>
        <br>

    </center>
</div>
</body>
</html>