DesignerWebsite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.shortcuts import render
from designers.models import Designers,Rawpass

from designers.forms import SendMail
from django.core.mail import send_mail
from django.conf import settings
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
import random
import string
from django.contrib.auth.hashers import make_password

from designers.models import Designers


def Mail(request):
    email=""
    if request.method == "POST":
        MyRegisterForm = SendMail(request.POST)
        if MyRegisterForm.is_valid():
            Send_To=MyRegisterForm.cleaned_data['Send_To']
            dbuser = Designers.objects.filter(email=Send_To)
            if dbuser:
                user=dbuser[0]
                randpass=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(8))
                dbuser[0].password=make_password(randpass)
                dbuser[0].designerID='GBIDX0{0}'.format(Designers.objects.count())
                rawpass=Rawpass(rawpass=randpass,designer=dbuser[0])
                rawpass.save()
                dbuser[0].save()
                contact_message =  'your userId and password is {0} {1}'.format(user.designerID,randpass)
                from_email = settings.EMAIL_HOST_USER
                to_email = []
                to_email.append(Send_To)
                send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)



        else:
            MyRegisterForm = SendMail(request.GET)

    return render(request, 'designers/SendMails.html',{})



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^designers/',include('designers.urls')),
    url(r'^',include('customers.urls')),
    #url(r'^store/', include('store.urls')),
    url(r'^mail/',  admin.site.admin_view(Mail), name='Mail'),
    url(r'^andro/',include('apis.urls')),
    #url(r'^seller/',include('seller.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apis/urls.py
from django.conf.urls import url
from functools import wraps
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name='apis'


def csrf_exempt(view_func):
    def wrapped_view(request,*args,**kwargs):
        return view_func(request,*args,**kwargs)
    wrapped_view.csrf_exempt=True
    return wraps(view_func,)(wrapped_view)


urlpatterns = format_suffix_patterns( [
    url(r'^hu/$', views.IndexViewSet.as_view()),
    url(r'^humi/$', csrf_exempt(views.Login.as_view())),
    url(r'^humis/$', csrf_exempt(views.SearchBlogs.as_view())),
    url(r'^ru/$', csrf_exempt(views.CreateBlog.as_view())),
    url(r'^rumi/$', csrf_exempt(views.DesignerBlogs.as_view())),
    url(r'^rumis/$', csrf_exempt(views.LikeView.as_view())),
    url(r'^sayonara/$', csrf_exempt(views.Logout.as_view())),



    url(r'^sl/$', csrf_exempt(views.StoreLogin.as_view())),
])

customers/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name='customers'


urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^designs$', views.search,name='search'),
    url(r'^blogs$',views.blogs,name='blogs'),
    url(r'^job_description$',views.job,name='job'),
    url(r'^job_personal$',views.job2,name='job2'),
    url(r'^designer_select$',views.designer,name='designer'),
    url(r'^designer_selected$',views.designer_selected,name='designer_selected'),
    url(r'^otp', views.otp, name='otp'),
    url(r'^make_payment$', views.make_payment, name='make_payment'),
    url(r'^successfull$',views.successfull, name='successfull'),
    url(r'^login$',views.login, name='login'),
    url(r'^logout$',views.logout, name='logout'),
    url(r'^profile_details',views.profile_handler,name='profile_handler'),
    url(r'^update_post',views.update,name="update"),
    url(r'^howitworks',views.howitworks,name='howitworks'),
    url(r'^ourdesign$',views.ourdesign,name='ourdesign'),
    #url(r'^testing$',views.testblogs,name='testblogs'),
    url(r'^blogview/$', views.specific_blog, name='specific_blog'),
    url(r'^resend$', views.resend, name='resend'),
    url(r'^test$', views.test, name='test'),










]

customers/models.py
from django.db import models
from designers.models import *

# Create your models here.
class Job(models.Model):
    roomtype = models.CharField(max_length=15)
    lifespan = models.CharField(max_length=20)
    execution = models.BooleanField(default=False)
    area = models.FloatField()
    estimatedbudget = models.IntegerField()
    requirements = models.TextField(max_length=200,blank=True,null=True)
    email=models.EmailField(max_length=100)
    designer=models.ForeignKey(Designers,on_delete=models.CASCADE)
    job_started=models.BooleanField(default=False)
    password=models.CharField(max_length=50)
    name=models.CharField(max_length=100,null=True)
    contact=models.CharField(max_length=14,null=True)
    date=models.DateTimeField(default=datetime.now())

    def __str__(self):
       return self.email



class Complains(models.Model):
    to=models.ForeignKey(Designers, on_delete=models.CASCADE,blank=True,null=True)
    by=models.ForeignKey(Job,on_delete=models.CASCADE)
    complain=models.CharField(max_length=2000)
    date=models.DateField(default=datetime.now())


class Updates(models.Model):
    job=models.ForeignKey(Job,on_delete=models.CASCADE)
    author=models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.now())
    image=models.ImageField(null=True,blank=True)
    article=models.TextField(max_length=500)
    designer=models.BooleanField(default=False)

    def __str__(self):
       return self.article

customers/forms.py
from django import forms

class BlogsForm(forms.Form):
    searchfield=forms.CharField()

class JobInitial(forms.Form):
    roomtype=forms.CharField()
    lifespan=forms.CharField()
    execution=forms.CharField()
    area=forms.FloatField()
    estimatedbudget=forms.IntegerField()
    #requirements=forms.CharField(required=False)
    false_ceiling=forms.CharField(required=False)
    flooring=forms.CharField(required=False)
    wall_paper=forms.CharField(required=False)
    wall_painting=forms.CharField(required=False)
    luxury_goods=forms.CharField(required=False)




class JobSecondStage(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    freetime=forms.DateTimeInput()
    contact=forms.CharField()

class Otp(forms.Form):
    otp=forms.CharField()


class LoginForm(forms.Form):
    email=forms.EmailField()
    password=forms.CharField()



class ComplainForm(forms.Form):
    complain=forms.CharField()
    time=forms.DateInput()


class DesignSearch(forms.Form):
    search=forms.CharField()


class Updatesform(forms.Form):
    image = forms.ImageField(required=False)
    article = forms.CharField(max_length=500)


class SelectBlog(forms.Form):
    url=forms.IntegerField()

customers/views.py
from django.shortcuts import render
from django.http import HttpResponse
from designers.models import Designers,Blogs
from .filters import CustomerSearchFilter,BlogSearchFilter
from .forms import *
from .models import *
from django.core.mail import send_mail
from django.conf import settings
from designers.models import *
from rest_framework import routers
from apis import views
from rest_framework.urlpatterns import format_suffix_patterns
import random
import string
from django.views.decorators.cache import cache_control
# Create your views here.

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    if  request.session.has_key('job'):

        del request.session['job']
    toppers=Designers.objects.order_by('-points')[:5]
    topper1=toppers[0]
    topper2 = toppers[1]
    topper3 = toppers[2]
    topper4 = toppers[3]
    topper5=toppers[4]

    content={
        'topper1':topper1,
        'topper2':topper2,
        'topper3':topper3,
        'topper4':topper4,
        'topper5':topper5
    }

    return render(request, 'customers/home.html', content)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def search(request):
    search_text=""
    designer=None
    designer_list=Designers.objects.all().order_by('-points')
    designer_filter=CustomerSearchFilter(request.GET, queryset=designer_list)
    if request.method == "POST":
        search_text = request.POST['search_text']
        if(search_text==""):
            designer=None
        else:
            designer = Designers.objects.filter(name__contains=search_text)

    if  request.session.has_key('job'):
        search_text = ""
        designer = None
        designer_list = Designers.objects.filter(PortfolioFilled=True).order_by('-points')
        designer_filter = CustomerSearchFilter(request.GET, queryset=designer_list)
        if request.method == "POST":
            search_text = request.POST['search_text']
            if (search_text == ""):
                designer = None
            else:
                designer = Designers.objects.filter(name__contains=search_text)

            return render(request, 'customers/ajax_search.html', {'designers': designer})
        return render(request, 'customers/search.html', {'filter': designer_filter, 'designers': designer})
    if  request.session.has_key('job'):

        del request.session['job']
    toppers=Designers.objects.order_by('-points')[:5]
    topper1=toppers[0]
    topper2 = toppers[1]
    topper3 = toppers[2]
    topper4 = toppers[3]
    topper5=toppers[4]

    content={
        'topper1':topper1,
        'topper2':topper2,
        'topper3':topper3,
        'topper4':topper4,
        'topper5':topper5
    }
    return render(request, 'customers/home.html',content )





@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def blogs(request):
    if  request.session.has_key('job'):

        del request.session['job']
    searchfield=""
    searchentry=BlogsForm(request.GET)
    blogList=Blogs.objects.filter().order_by('-day')
    if searchentry.is_valid():
        blogList = []
        searchfield=list(set(searchentry.cleaned_data['searchfield'].split(sep=" ")))
        for x in searchfield:
            newBlogs = Blogs.objects.filter(title__contains=x)
            print(len(newBlogs))
            if len(newBlogs)<3and len(newBlogs)>0:
                blogList.extend(newBlogs)
                blogList = list(set(blogList))
            newBlogs1 = Blogs.objects.filter(subject__contains=x)
            if len(newBlogs1)<3 and len(newBlogs1)>0:
                blogList.extend(newBlogs1)
                blogList = list(set(blogList))

    content={'blogList':blogList}




    return render(request,'customers/blogs.html',content)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def job(request):
    try :
        print(request.session['job'])
    except:
        pass
    if request.method=="POST":

        jobinitial=JobInitial(request.POST)
        print(jobinitial.errors)
        if jobinitial.is_valid():
            resultset=[]
            roomtype = jobinitial.cleaned_data['roomtype']
            resultset.append(roomtype)
            lifespan = jobinitial.cleaned_data['lifespan']
            resultset.append(lifespan)
            choice = jobinitial.cleaned_data['execution']

            if choice=="Yes":
                execution=True
            else:
                execution=False
            resultset.append(execution)
            area = jobinitial.cleaned_data['area']
            resultset.append(area)
            estimatedbudget =jobinitial.cleaned_data['estimatedbudget']
            resultset.append(estimatedbudget)

            reqr=[]
            #requirements=requirements+jobinitial.cleaned_data['false_ceiling']
            if jobinitial.cleaned_data['false_ceiling']=='on':
                reqr.append('False Ceiling')
            if jobinitial.cleaned_data['flooring']=='on':
                reqr.append('Flooring')
            if jobinitial.cleaned_data['wall_paper']=='on':
                reqr.append('Wall Paper')
            if jobinitial.cleaned_data['wall_painting']=='on':
                reqr.append('Wall painting')
            if jobinitial.cleaned_data['luxury_goods']=='on':
                reqr.append('Luxury Goods')
            requirements = ",".join(reqr)
            #print(requirements)
            resultset.append(requirements)
            request.session['job'] = resultset
            print("{0}".format(request.session['job']))
            designer_list = Designers.objects.filter(PortfolioFilled=True).order_by('-points')
            designer_filter = CustomerSearchFilter(request.GET, queryset=designer_list)
            return render(request, 'customers/search.html', {'filter': designer_filter})
    if  request.session.has_key('job'):

        del request.session['job']
    toppers=Designers.objects.order_by('-points')[:5]
    topper1=toppers[0]
    topper2 = toppers[1]
    topper3 = toppers[2]
    topper4 = toppers[3]
    topper5=toppers[4]

    content={
        'topper1':topper1,
        'topper2':topper2,
        'topper3':topper3,
        'topper4':topper4,
        'topper5':topper5
    }

    return render(request,'customers/home.html',content)


def job2(request):

    if request.method=="POST":


        jobsecond=JobSecondStage(request.POST)
        print(jobsecond.errors)
        if jobsecond.is_valid():
            resultset=request.session['job']
            email = request.POST['email']
            resultset.append(email)
            freetime = request.POST['freetime']
            contact=request.POST['contact']
            resultset.append(freetime)
            name=request.POST['name']
            resultset.append(name)
            resultset.append(contact)
            request.session['job']=resultset
            print(request.session['job'])
            contact_message = 'your userId and password is {0}'.format(resultset[7])
            from_email = settings.EMAIL_HOST_USER
            to_email = []
            to_email.append(resultset[8])
            send_mail('Registration Succesfull', contact_message, from_email, to_email, fail_silently=False)

            return render(request,'customers/otp.html',{})
    return render(request,'customers/job2.html',{})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def designer(request):
    if request.session.has_key('job'):
        designer = None
        if request.method == "POST":
            designer = Designers.objects.filter(designerID=request.POST['designer'])
            print(designer)
            blogList = Blogs.objects.filter(author=Designers.objects.filter(designerID=request.POST['designer'])).order_by('-dated')
            return render(request, 'customers/designerselect.html', {'designer': designer,'blogList': blogList})
        return render(request, 'customers/designerselect.html', {'designer': designer})
    if  request.session.has_key('job'):

        del request.session['job']
    toppers=Designers.objects.order_by('-points')[:5]
    topper1=toppers[0]
    topper2 = toppers[1]
    topper3 = toppers[2]
    topper4 = toppers[3]
    topper5=toppers[4]

    content={
        'topper1':topper1,
        'topper2':topper2,
        'topper3':topper3,
        'topper4':topper4,
        'topper5':topper5
    }
    return render(request, 'customers/home.html', content)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def designer_selected(request):
    email=""
    if request.session.has_key('job'):
        if request.method=="POST":
            resultset=request.session['job']
            designer=request.POST['designerselected']
            resultset.append(designer)
            randpass = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(6))
            print(randpass)
            resultset.append(randpass)
            request.session['job']=resultset
            print(request.session['job'])


            return render(request, 'customers/job2.html', {})
        else:
            return render(request, 'customers/job2.html', {})
    if  request.session.has_key('job'):

        del request.session['job']
    toppers=Designers.objects.order_by('-points')[:5]
    topper1=toppers[0]
    topper2 = toppers[1]
    topper3 = toppers[2]
    topper4 = toppers[3]
    topper5=toppers[4]

    content={
        'topper1':topper1,
        'topper2':topper2,
        'topper3':topper3,
        'topper4':topper4,
        'topper5':topper5
    }
    return render(request, 'customers/home.html',content)



@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def otp(request):
    if request.session.has_key('job'):
        if request.method=="POST":
            otp = Otp(request.POST)
            print(otp.errors)
            if otp.is_valid():
                resultset = request.session['job']
                otppass=otp.cleaned_data['otp']

customers/templates/customers/ajax_search.html
{% if designers.count > 0 %}


{% for  designer in designers %}
  <li>{{designer.name}}</li>
{% endfor %}

{% endif %}

customers/templates/customers/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form method="post" action="{% url 'customers:login' %}">
        {% csrf_token %}
        <input name="email" type="text">
        <input name="password" type="password">
        <button type="submit">Login</button>
    </form>
</body>
</html>

customers/templates/customers/job_detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'customers/img/favicon.png' %}"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{job.name}} - My Project</title>
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/projectdashboard.css' %}">
    <link rel="stylesheet" href="{% static 'customers/css/template.css' %}">


</head>


<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <center>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </center>
            </button>

            <a class="navbar-brand" href="{% url 'customers:index' %}"><img src="{% static 'customers/img/GharBanaoLogo_nav.png' %}"></a>
        </div>


        <div class="collapse navbar-collapse" id="navbar">


            <ul class="nav navbar-nav navbar-right">
                <!--<li><a href="{% url 'customers:howitworks' %}">How it works<span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'customers:ourdesign' %}">Designs<span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'customers:blogs' %}">Blog<span class="sr-only">(current)</span></a></li>-->
                <li><a href="{% url 'customers:logout' %}" class="btn my_project">Logout</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!-- End of nav -->

<div class="container-fluid page" id="page">
    <!-- Page Starts-->
    <div class="row no-margin">
        <div class="col-xs-2 no-padding page-nav">
            <ul class="tab-links">
                <li >
                    <a data-toggle="tab" href="#update">Post update</a>
                </li>

                <li >
                    <a data-toggle="tab" href="#feed">Updates feed</a>
                </li>

                <li >
                    <a data-toggle="tab" href="#details">Project details</a>
                </li>

                <li >
                    <a data-toggle="tab" href="#designer">Your designer</a>
                </li>

                <li >
                    <a data-toggle="tab" href="#contacts" >Contact details</a>
                </li>
                <li>
                    <a href="{% url 'customers:login' %}" >Refresh</a>
                </li>
            </ul>
        </div>

        <div class="col-sm-6 no-padding tab-content">

            <div id="update" class="col-xs-12 tab-pane fade in active">
                <div class="row no-margin block">
                    <h3>Have an update? Post here</h3>

                    <form action="{% url 'customers:update' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row no-margin"><textarea class="post-text" name="article" placeholder="Enter your update here"></textarea></div><br>
                        <div class="col-sm-6 no-padding"><input type="file" name="image"></div>
                        <div class="col-sm-6 no-padding"><button type="submit" class="submit-btn">Submit</button></div>
                    </form>
                </div>

                <div class="row no-margin block">
                    <h4>Recent Updates</h4>
                    {% for x in u|slice:":10" %}
                    <div class="row no-margin">
                        <p> <span  class="recent-author">{{x.author}} : </span> {{x}}
                            {% if x.image %}
                            <img src="{% static 'designers/img/attachment.png'%}">
                            {% endif %}
                            <span class="recent-time"> <i> on {{x.date}}</i> </span> </p>
                    </div>
                    {% endfor %}
                </div>

            </div>

            <div id="feed" class="col-xs-12 tab-pane fade">
                <div class="row no-margin main-info updates">
                    {% for x in u %}
                    <div class="row no-margin block">
                        <div class="col-sm-1 col-xs-2 no-padding">

                            {% if x.designer %}

                            <div class="profpic" style="background: url({{d.profilepic.url}}) no-repeat center; background-size: cover"></div>
                            {% else %}
                            <img src="{% static 'customers/img/face1.jpg'%}" class="img-responsive">
                            {% endif %}

                        </div>
                        <div class="col-sm-11 col-xs-10 ">
                            <p class="author"><b>{{x.author}}</b></p>

                            <p class="update-content">

                                <i>"{{x}}"</i>
                            </p>
                            {% if x.image %}
                            <img src="{{x.image.url}}" class="img-responsive">

                            {% endif %}
                            <p class="daye">{{x.date}}</p>

                        </div>
                    </div>
                    {% endfor %}
                </div>
                <br>
            </div>

            <div id="details" class="col-xs-12 tab-pane fade">
                <div class="row table-responsive table-info block">
                    <table class="table">

                        <h3>Project Details</h3>
                        <br>

                        <tbody>
                        <tr>
                            <td><b>Room-type:</b></td>
                            <td><span class="blue_color">{{job.roomtype}}</span></td>
                        </tr>
                        <tr>
                            <td><b>Property-type:</b></td>
                            <td><span class="blue_color">{{ job.lifespan}}</span></td>
                        </tr>
                        <tr>
                            <td><b>Area:</b></td>
                            <td><span class="blue_color">{{job.area}} sqm</span></td>
                        </tr>
                        <tr>
                            <td><b>Estimated Budget:</b></td>
                            <td><span class="green_color">{{job.estimatedbudget}}</span></td>
                        </tr>
                        <tr>
                            <td><b>Requirements:</b></td>
                            {% if j.requirements %}
                            <td><span class="blue_color">{{job.requirements}}</span></td>
                            {% else %}
                            <td><span class="blue_color">N/A</span></td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td><b>Projects-type:</b></td>
                            {% if job.execution %}
                            <td><span class="execution">Design + Implementation</span></td>
                            {% else %}
                            <td><span class="design">Design</span></td>
                            {% endif %}
                        </tr>


                        </tbody>

                    </table>
                </div>
            </div>

            <div id="designer" class="col-xs-12 tab-pane fade">
                <div class="row no-margin block">
                    <div class="col-xs-3">
                        <img src="{{d.profilepic.url}}" class="img-responsive">
                    </div>

                    <div class="col-xs-9">
                        <p class="dname"><b>{{d.name}}</b></p>
                        <p class="dfirm">{{d.firmname}}</p>
                        <p class="dpoints">Gharanao Points: {{d.points}}</p>

                    </div>
                </div>

                <div class="row no-margin block">
                    <h3>Portfolio</h3><hr>
                    <div class="col-sm-4"><img src="{{d.design1.url}}" class="img-responsive"></div>
                    <div class="col-sm-4"><img src="{{d.design2.url}}" class="img-responsive"></div>
                    <div class="col-sm-4"><img src="{{d.design3.url}}" class="img-responsive"></div>
                </div>

                <div class="row no-margin block">
                    <h3>About the designer</h3>
                    <hr>
                    <h5>{{d.AboutMe}}</h5>
                </div>

                <div class="row no-margin block">
                    <h3>About the designs</h3>
                    <hr>
                    <h5>{{d.AboutYourDesigns}}</h5>
                </div>

            </div>

            <div id="contacts" class="col-xs-12 tab-pane fade">

                <div class="row no-margin cont-profile block">
                    <div class="col-xs-4 no-padding cont_pro"  style="background: url({{d.profilepic.url}}) no-repeat center; background-size: cover;">

                    </div>

                    <div class="col-xs-8">
                        <h3>Designer contact details</h3>
                        <hr>
                        <h5><b>Email ID:</b> {{d.email}} </h5>
                        <h5><b>Phone no:</b> {{d.contact}} </h5>
                    </div>
                </div>

                <div class="row no-margin cont-profile block">
                    <div class="col-xs-4 no-padding cont_pro"  style="background: url({% static 'customers/img/face1.jpg'%}) no-repeat center; background-size: cover;">

                    </div>

                    <div class="col-xs-8">
                        <h3>Customer contact details</h3>
                        <hr>
                        <h5><b>Email ID:</b> {{job.email}} </h5>
                        <h5><b>Phone no:</b> {{job.contact}} </h5>
                    </div>
                </div>

            </div>

        </div>

        <div class="col-sm-4 no-padding common-col">
            <div class="col-xs-12 no-padding block">
                <h4>Recent pictures</h4>
                <hr>
                {% for x in u|slice:":12" %}
                {% if x.image %}
                <div class="col-xs-4 no-padding">
                    <div class="row no-margin recent-pic" style="background: url({{x.image.url}}) no-repeat center; background-size: cover;">

                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>

            <div class="col-xs-12 no-padding block">
                <h4>Complaints</h4><hr>
                <form action="{% url 'customers:profile_handler' %}" method="get">
                    <textarea name="complain" class="complaint-form" placeholder="Write your complaints here (if any)"></textarea><br>
                    <button type="submit" class="submit-btn">Submit</button>
                </form>
            </div>
        </div>
    </div>





    <!--footer-->
    <div class="container footer">
        <div class="row"><!-- row -->

            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 tyc"><!-- widgets column center -->
                <img class="img-responsive" src="{% static 'customers/img/logo_bw.png' %}">
            </div>

            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">


                <div class="col-sm-4 col-xs-6 mycol list"><!-- widgets column left -->

                    <h4 class="title-widget">COMPANY</h4>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Designers</a></li>
                        <li><a href="#">Feedback</a></li>
                        <li><a href="#">Support</a></li>
                    </ul>


                </div><!-- widgets column left end -->

                <div class="col-sm-4 col-xs-6 mycol list"><!-- widgets column left -->

                    <h4 class="title-widget">LEGAL</h4>
                    <ul>
                        <li><a  href="#">Terms and Conditions</a></li>
                        <li><a  href="#">Privacy Policy</a></li>
                        <li><a  href="#">Payment Securities</a></li>
                        <li><a  href="#">Partners</a></li>
                    </ul>
                </div><!-- widgets column left end -->



                <div class="col-sm-4 col-xs-12 mycol list"><!-- widgets column left -->
                    <h4 class="title-widget">CONNECT</h4>
                    <div class="social-icons">
                        <a href="https://www.facebook.com/GharBanao/"><img src="{% static 'customers/img/fb.png' %}"></a>
                        <a href="https://twitter.com/GharBanao"><img src="{% static 'customers/img/tweet.png' %}"></a>
                        <a href="https://www.linkedin.com/company-beta/10652164/"><img src="{% static 'customers/img/in.png' %}""></a><br>
                    </div>
                </div>
            </div>
        </div>
        <center><p class="copyright"> Copyright © 2017 Tune Your Construction (P) Ltd.</p></center>
    </div>



</div>
<script src="{% static 'customers/js/jquery.min.js' %}"></script>
<script src="{% static 'customers/js/bootstrap.min.js' %}"></script>
<!--<script>
         $(document).ready(function(){
             $(".recent-pic").width($(".recent-pic").height());
         });
    </script>-->
</body>
</html>

customers/templates/customers/make_payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>make_payment</title>
</head>
<body>
<form>
    <button type="submit" >make payment</button>
</form>
</body>
</html>